PLATFORMS=telos telosb
COMPONENT=Sarp
PFLAGS=-I%T/lib/Counters -I%T/../apps/sarp-0.4-dev/includes -I%T/../apps/sarp-0.4-dev/modules -I%T/../apps/sarp-0.4-dev/interfaces -DDEBUG -DONOFFATTACK -DSARP04 -DPREDICTABILITY -DDYNAMIC_FORGETTING -D__REAL__MOTE__ -I%T/lib/Util
include ../Makerules
