COMPONENT=Sarp
PFLAGS=-I%T/lib/Counters -I%T/interfaces -I%T/../apps/sarp-0.2-dev/includes -I%T/../apps/sarp-0.2-dev/modules -I%T/../apps/sarp-0.2-dev/interfaces -D__REAL__MOTE__
include ../Makerules
