#!/bin/sh
rm -rf data-dir
mkdir data-dir
DDIR=$PWD/data-dir
mkdir -p $DDIR/CONTROL
mkdir -p $DDIR/usr/local/bin
mkdir -p $DDIR/usr/local/lib
mkdir -p $DDIR/opt/QtPalmtop/pics
mkdir -p $DDIR/opt/QtPalmtop/apps/Jeode

cp control $DDIR/CONTROL
cp scythe.png $DDIR/opt/QtPalmtop/pics
cp field.desktop $DDIR/opt/QtPalmtop/apps/Jeode
cp runfield $DDIR/usr/local/bin

cd ../../../../..
jar cfm $DDIR/usr/local/lib/field-tool.jar $DDIR/../field-tool.manifest net/tinyos/task/awtfield/*.class net/tinyos/message/*.class net/tinyos/packet/*.class net/tinyos/util/*.class

cd ../src/sf
make asf
cp asf $DDIR/usr/local/bin
