#!/bin/sh
rm -rf data-dir
mkdir data-dir
DDIR=$PWD/data-dir
mkdir -p $DDIR/CONTROL
mkdir -p $DDIR/usr/local/bin
mkdir -p $DDIR/usr/local/lib
mkdir -p $DDIR/opt/QtPalmtop/pics
mkdir -p $DDIR/opt/QtPalmtop/apps/Jeode

cp control $DDIR/CONTROL
cp scythe.png $DDIR/opt/QtPalmtop/pics
cp spy.desktop $DDIR/opt/QtPalmtop/apps/Jeode
cp runspy $DDIR/usr/local/bin

cd ../../../../..
jar cfm $DDIR/usr/local/lib/spy-tool.jar $DDIR/../spy-tool.manifest net/tinyos/task/spy/*.class net/tinyos/message/*.class net/tinyos/packet/*.class net/tinyos/util/*.class
